apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /etc/grafana/provisioning/datasources/influxdb-datasource.yaml
          name: grafana-config
          readOnly: true
          subPath: influxdb-datasource.yaml
        - mountPath: /etc/grafana/provisioning/dashboards/grafana-dashboard-provider.yaml
          name: grafana-config
          readOnly: true
          subPath: grafana-dashboard-provider.yaml
        - mountPath: /var/lib/grafana/dashboards/nginx-dashboard.json
          name: grafana-config
          readOnly: true
          subPath: nginx-dashboard.json
        - mountPath: /var/lib/grafana/dashboards/mysql-dashboard.json
          name: grafana-config
          readOnly: true
          subPath: mysql-dashboard.json
        - mountPath: /var/lib/grafana/dashboards/phpmyadmin-dashboard.json
          name: grafana-config
          readOnly: true
          subPath: phpmyadmin-dashboard.json
        - mountPath: /var/lib/grafana/dashboards/wordpress-dashboard.json
          name: grafana-config
          readOnly: true
          subPath: wordpress-dashboard.json
        - mountPath: /var/lib/grafana/dashboards/influxdb-dashboard.json
          name: grafana-config
          readOnly: true
          subPath: influxdb-dashboard.json
        - mountPath: /var/lib/grafana/dashboards/telegraf-dashboard.json
          name: grafana-config
          readOnly: true
          subPath: telegraf-dashboard.json
        - mountPath: /var/lib/grafana/dashboards/grafana-dashboard.json
          name: grafana-config
          readOnly: true
          subPath: grafana-dashboard.json
        ports:
        - containerPort: 3000
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config
