apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  selector:
    app: ftps
  ports:
    - protocol: TCP
      port: 21
      targetPort: 21
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: secrets
        name: ftps
        image: mikatux/ftps-server
        ports:
        - containerPort: 21
