apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    app: telegraf
  ports:
  - protocol: UDP
    port: 8125
    targetPort: 8125
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - image: telegraf
        name: telegraf
        volumeMounts:
          - mountPath: /etc/telegraf/telegraf.conf
            name: telegraf-configmap
            subPath: telegraf.conf
            readOnly: true
        envFrom:
          - secretRef:
              name: secrets
      volumes:
        - name: telegraf-configmap
          configMap:
            name: telegraf-configmap
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
