apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: active-port
      protocol: TCP
      port: 20
      targetPort: 20
    - name: passive-zero
      protocol: TCP
      port: 21000
      targetPort: 21000
    - name: passive-one
      protocol: TCP
      port: 21001
      targetPort: 21001
    - name: passive-two
      protocol: TCP
      port: 21002
      targetPort: 21002
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
